---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

tasks:

  clean:
    desc: Clean files and directories no longer needed after cluster bootstrap
    cmds:
      # Clean up CI
      - rm -rf {{.ROOT_DIR}}/.github/tests
      - rm -rf {{.ROOT_DIR}}/.github/workflows/e2e.yaml
      # Move bootstrap directory to gitignored directory
      - mkdir -p {{.ROOT_DIR}}/.private
      - mv {{.ROOT_DIR}}/bootstrap {{.ROOT_DIR}}/.private/bootstrap-{{now | date "150405"}}
      # Update renovate.json5
      - sed -i {{if eq OS "darwin"}}''{{end}} 's/(..\.j2)\?(..\.j2)\?//g' {{.ROOT_DIR}}/.github/renovate.json5
      - sed -i {{if eq OS "darwin"}}''{{end}} '/addons/d' {{.ROOT_DIR}}/.github/renovate.json5
    preconditions:
      - { msg: "bootstrap dir not found",  sh: "test -d {{.ROOT_DIR}}/bootstrap" }
      - { msg: "renovate.json5 not found", sh: "test -f {{.ROOT_DIR}}/.github/renovate.json5" }

  reset:
    desc: Remove templated configuration files
    prompt: Remove templated configuration files... continue?
    cmds:
      - rm -rf {{.ROOT_DIR}}/.sops.yaml
      - rm -rf {{.ROOT_DIR}}/k0s-config.yaml
      - rm -rf {{.ROOT_DIR}}/ansible
      - rm -rf {{.ROOT_DIR}}/kubernetes

  reset-repo:
    desc: Set repo back to HEAD
    prompt: Set repo back to HEAD... continue?
    cmds:
      - task: reset
      - git reset --hard HEAD
      - git clean -f -d
      - git pull
